### ISSUE TITLE
Fixer UTF-8

### ISSUE THREAD

**Issue by mkody** [asbf/website#1]
Les mails ont des problèmes d'accents au niveau du sujet.

**Comment by heuzef** [comment]
Si je peux me permettre, y'a toujours des problème d'encodage sur le formulaire de contact, il faudrait réouvrir ce ticket ;)

**Comment by mkody** [comment]
A quel endroit ? Le contenu, le sujet ? Quel formulaire ?

**Comment by heuzef** [comment]
Formulaire de contact > Qui contacter.

C'est peut-être un bug de chez moi, car quand je change d'onglet le problème disparait :/

**Comment by heuzef** [comment]
Ha non c'est quand je déplois la liste plusieur fois, c'est donc un bug JS je pense.

**Comment by mkody** [comment]
J'utilise pas de javascript en plus sur le select, c'est géré par le naviguateur.
